# Functions to print the language codes for
# the Google and Microsoft Translation APIs

languages <- list(
    Google = list(
        Afrikaans =             'af',
        Albanian =              'sq',
        Arabic =                'ar',
        Armenian =              'hy',
        Azerbaijani =           'az',
        Basque =                'eu',
        Belarusian =            'be',
        Bengali =               'bn',
        Bosnian =               'bs',
        Bulgarian =             'bg',
        Catalan =               'ca',
        Cebuano =               'ceb',
        Chinese_Simplified =    'zh-CN',
        Chinese_Traditional =   'zh-TW',
        Croatian =              'hr',
        Czech =                 'cs',
        Danish =                'da',
        Dutch =                 'nl',
        English =               'en',
        Esperanto =             'eo',
        Estonian =              'et',
        Filipino =              'tl',
        Finnish =               'fi',
        French =                'fr',
        Galician =              'gl',
        Georgian =              'ka',
        German =                'de',
        Greek =                 'el',
        Gujarati =              'gu',
        Haitian_Creole =        'ht',  
        Hausa =                 'ha',
        Hebrew =                'iw',
        Hindi =                 'hi',
        Hmong =                 'hmn',
        Hungarian =             'hu',
        Icelandic =             'is',
        Igbo =                  'ig',
        Indonesian =            'id',
        Irish =                 'ga',
        Italian =               'it',
        Japanese =              'ja',
        Javanese =              'jw',
        Kannada =               'kn',
        Khmer =                 'km',
        Korean =                'ko',
        Lao =                   'lo',
        Latin =                 'la',
        Latvian =               'lv',
        Lithuanian =            'lt',
        Macedonian =            'mk',
        Malay =                 'ms',
        Maltese =               'mt',
        Maori =                 'mi',
        Marathi =               'mr',
        Mongolian =             'mn',
        Nepali =                'ne',
        Norwegian =             'no',
        Persian =               'fa',
        Polish =                'pl',
        Portuguese =            'pt',
        Punjabi =               'pa',
        Romanian =              'ro',
        Russian =               'ru',
        Serbian =               'sr',
        Slovak =                'sk',
        Slovenian =             'sl',
        Somali =                'so',
        Spanish =               'es',
        Swahili =               'sw',
        Swedish =               'sv',
        Tamil =                 'ta',
        Telugu =                'te',
        Thai =                  'th',
        Turkish =               'tr',
        Ukrainian =             'uk',
        Urdu =                  'ur',
        Vietnamese =            'vi',
        Welsh =                 'cy',
        Yiddish =               'yi',
        Yoruba =                'yo',
        Zulu =                  'zu'
        ),

    Microsoft = list(
        Arabic =                'ar',
        Bulgarian =             'bg',
        Catalan =               'ca',
        Chinese_Simplified =    'zh-CHS',
        Chinese_Traditional =   'zh-CHT',
        Czech =                 'cs',	
        Danish =                'da',
        Dutch =                 'nl',
        English =               'en',
        Estonian =              'et',
        Finnish =               'fi',
        French =                'fr',
        German =                'de',
        Greek =                 'el',
        Haitian_Creole =        'ht',
        Hebrew =                'he',
        Hindi =                 'hi',
        Hmong_Daw =             'mww',
        Hungarian =             'hu',
        Indonesian =            'id',
        Italian =               'it',
        Japanese =              'ja',
        Klingon =               'tlh',
        Klingon_pIqaD =         'tlh-Qaak',
        Korean =                'ko',
        Latvian =               'lv',
        Lithuanian =            'lt',
        Malay =                 'ms',
        Maltese =               'mt',
        Norwegian =             'no',
        Persian =               'fa',
        Polish =                'pl',
        Portuguese =            'pt',
        Romanian =              'ro',
        Russian =               'ru',
        Slovak =                'sk',
        Slovenian =             'sl',
        Spanish =               'es',
        Swedish =               'sv',
        Thai =                  'th',
        Turkish =               'tr',
        Ukrainian =             'uk',
        Urdu =                  'ur',
        Vietnamese =            'vi',
        Welsh =                 'cy'
        )
    )

getMicrosoftLanguages <- function(){
    getLanguages('Microsoft')
}

getGoogleLanguages <- function(){
    getLanguages('Google')
}

getLanguages <- function(language){
    cat('LANGUAGE                CODE
----------------------------
')
    for(i in 1:length(languages[[language]])){
        code <- languages[[language]][i]
        cat(paste(gsub('_', ' ', names(code)), paste(rep(" ", 22 - nchar(names(code))), collapse=''), code))
        cat('\n')
    }
}
